services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DEV_DB_DATABASE}
      POSTGRES_USER: ${DEV_DB_USERNAME}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "${DEV_DB_PORT}:5432"